routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes([
  // 'register' => true,
  // 'reset' => true,
  'verify' => true,
]);

Route::get('/forbidden', function () {
  return view('error.forbidden');
});

Route::group(['middleware' => ['verified']], function () {
  Route::get('/', 'HomeController@index')->name('dashboard');
  Route::get('/home', 'HomeController@index')->name('dashboard.index');
  Route::get('/dashboard', 'HomeController@index')->name('dashboard');

  Route::get('/notification', 'NotificationController@index');
  Route::get('/notification/get/{id?}', 'NotificationController@get');
  Route::get('/notification/read-all', 'NotificationController@read_all');
  Route::get('/notification/delete-all', 'NotificationController@delete_all');
  Route::get('/notification/view/{id?}', 'NotificationController@view');

  Route::get('/account', 'AccountController@show')->name('account');
  Route::post('/account/change-password', 'AccountController@change_password_process')->name('account.pass');
  Route::post('/account/update', 'AccountController@update_process')->name('account.update');
  Route::post('/account/update-fcm', 'AccountController@update_fcm')->name('account.update_fcm');
  Route::post('/account/update-avatar', 'AccountController@change_avatar_process')->name('account.avatar');

  Route::resource('roles', RoleController::class);
  Route::get('/roles/delete/{id?}', 'RoleController@destroy')->name('roles.delete');
  Route::post('/roles/update/{id?}', 'RoleController@update')->name('roles.update_process');

  Route::resource('permissions', PermissionController::class);
  Route::get('/permissions/delete/{id?}', 'PermissionController@destroy')->name('permissions.delete');
  Route::post('/permissions/update/{id?}', 'PermissionController@update')->name('permissions.update_process');

  Route::resource('users', UsersController::class);
  Route::get('/users/delete/{id?}', 'UsersController@destroy')->name('users.delete');
  Route::post('/users/update/{id?}', 'UsersController@update')->name('users.update_process');

  Route::resource('actions', ActionController::class);
  Route::get('/actions/delete/{id?}', 'ActionController@destroy')->name('actions.delete');
  Route::post('/actions/update/{id?}', 'ActionController@update')->name('actions.update_process');

  Route::resource('menus', MenuController::class);
  Route::get('/menus/delete/{id?}', 'MenuController@destroy')->name('menus.delete');
  Route::post('/menus/update/{id?}', 'MenuController@update')->name('menus.update_process');

  Route::resource('category', CategoryController::class);
  Route::get('/category/delete/{id?}', 'CategoryController@destroy')->name('category.delete');
  Route::post('/category/update/{id?}', 'CategoryController@update')->name('category.update_process');

  Route::resource('report-level', ReportLevelController::class);
  Route::get('/report-level/delete/{id?}', 'ReportLevelController@destroy')->name('report-level.delete');
  Route::post('/report-level/update/{id?}', 'ReportLevelController@update')->name('report-level.update_process');

  Route::resource('risk-level', RiskLevelController::class);
  Route::get('/risk-level/delete/{id?}', 'RiskLevelController@destroy')->name('risk-level.delete');
  Route::post('/risk-level/update/{id?}', 'RiskLevelController@update')->name('risk-level.update_process');

  Route::resource('report', ReportController::class);
  Route::get('/report/print/{id?}', 'ReportController@print')->name('report.print');
  Route::get('/report/delete/{id?}', 'ReportController@destroy')->name('report.delete');
  Route::post('/report/update/{id?}', 'ReportController@update')->name('report.update_process');

  Route::resource('ranking', RankingController::class);
});

resources/views/layouts/components/navbar.blade.php
<!-- Main navbar -->
	<div class="navbar navbar-expand-md navbar-dark bg-{{ config('app.theme') }}-600">
		<a href="{{ url('/') }}" class="text-light" style="margin-top:10px;font-size:20px;margin-right:180px;">
			{{ config('app.name') }}
		</a>

		<div class="d-md-none">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
                <i class="icon-user-tie"></i>
            </button>
            <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
                <i class="icon-paragraph-justify3"></i>
            </button>
        </div>

		<div class="collapse navbar-collapse" id="navbar-mobile">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
						<i class="icon-paragraph-justify3"></i>
					</a>
				</li>
			</ul>

			<ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown">
                        <i class="icon-bell2"></i>
                        <span class="d-md-none ml-2">Notifications</span>
                        <span class="badge badge-pill bg-warning-400 ml-auto ml-md-0" id="jumlah_notif"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                        <div class="dropdown-content-header" style="">
                            <span class="font-weight-semibold">Notifications</span>
                            <button  type="button" class="btn btn-mark-read  btn-link btn-sm align-self-start ml-3" style="margin-top:-10px;">Mark all as read </button>
                            <input  type="hidden" value="0" id="last_id" >
                        </div>
                        <div class="dropdown-content-body dropdown-scrollable" style="padding: 0px !important;">
                            <ul class="media-list" id="notification">
                                <li class="media py-3 px-3 ">
									<div class="media-body">
										<span class="text-muted"><i class="icon-spinner4 spinner"></i> Loading </span>
									</div>
								</li>
                            </ul>
                        </div>
                        <div class="dropdown-content-footer justify-content-center p-0">
                            <a href="{{ url('/notification') }}" class="bg-light text-grey w-100 py-2" data-popup="tooltip" title="Lihat selengkapnya"><i class="icon-menu7 d-block top-0"></i></a>
                        </div>
                    </div>
                </li>
				<li class="nav-item dropdown dropdown-user">
					<a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ asset('assets/avatar/'.Auth::user()->avatar)  }}" class="rounded-circle mr-2 border border-light" height="34" width="34" alt="">
                        <span>{{ Auth::user()->name }}</span>
					</a>

					<div class="dropdown-menu dropdown-menu-right">
						<a href="{{ url('account') }}" class="dropdown-item"><i class="icon-user"></i> Your Profile</a>
						<a href="{{ url('account#password_change') }}" class="dropdown-item"><i class="icon-cog5"></i> Change Password</a>
						<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="dropdown-item"><i class="icon-switch2"></i> Logout</a>
                    </div>
				</li>
			</ul>
		</div>
	</div>
<!-- /main navbar -->

<script>
    $(document).ready(function() {
        notification();
        setInterval(notification, 5000);
        var baseurl = "{{ url('') }}";
        $(".btn-mark-read").hide();
        $('#jumlah_notif').hide();

        function notification() {
            let last_id = $('#last_id').val();
            $.ajax({
                url: "{{ url('notification/get') }}/"+last_id,
                contentType: "application/json",
                cache: false,
                dataType: 'json',
                success: function(result) {
                    var notif = "";
                    if (result.status && result.all != 0) {
                        $.each(result.content, function(i, item) {
                            var trimmedString = item.message.length > 150 ?
                                item.message.substring(0, 150 - 3) + "..." :
                                item.message;
                            let status = ''
                            if (item.is_seen == "1") {
                                status = 'background-color:#efefef !important;'
                            }
                            let link = "{{ url('notification/view/') }}";
                            notif += `
                                <li class="media pb-1" style="margin-top:0px !important;padding: 0.625rem 1.25rem 0.625rem 1.25rem;${status}">
                                    <div class="mr-2 position-relative">
                                        <div  class="btn border-2 border-${item.type} alpha-${item.type} text-${item.type}-800 btn-icon rounded-round "><i class="icon-bell3"></i></div>
                                    </div>
                                    <div class="media-body">
                                        <a href="${link+'/'+item.id}" style="text-decoration:none;">
                                            <div class="media-title">
                                                    <span class="font-weight-semibold text-dark">${item.title}</span>
                                            </div>
                                            <span class="text-muted">${trimmedString}</span> <br/>
                                            <span class="text-info font-size-sm"><i class="icon-calendar icon-sm"></i>  ${item.date} WIB</span>
                                        </a>
                                    </div>
								</li>
                            `;
                        });
                        if (result.unseen >= 1) {
                            $(".btn-mark-read").show();
                            $("#jumlah_notif").show();
                            $('#jumlah_notif').text(result.unseen);
                        } else {
                            $(".btn-mark-read").hide();
                            $('#jumlah_notif').hide();
                        }
                        $('#notification').html(notif);
                    } else {
                        notif = '<li class="media">' +
                            '<div class="media-body px-3 pb-3">' +
                            '<div class="text-muted text-center">Tidak ada notifikasi</div>' +
                            '</div>' +
                            '</li>';
                        $('#notification').html(notif);
                    }
                    //last_id
                    $('#last_id').val(result.last_id);

                    // check new notif
                    if(result.new > 0){
                        let notif = result.new > 1 ? `You have ${result.new} new notifications` : `You have a new notification`;
                        new Noty({
                                    text: '<i class="icon-bell3"></i> '+notif,
                                    type: 'info',
                                    timeout: 3000,
                                }).show();
                        $('title').html(notif+' - ');
                        // titleMarquee();
                        document.getElementById('audio-notif').play();
                    }

                },
                error: function() {
                    console.warn('Notification interval has been fail!');
                }
            })
        }

        $('.btn-mark-read').click(() => {
            $('.btn-mark-read').prop('disabled', true).html('<i class="icon-spinner4 spinner"></i> Loading')
            $.ajax({
                url: "{{ url('notification/read-all/') }}",
                contentType: "application/json",
                cache: false,
                dataType: 'json',
                success: function(result) {
                    swalInit.fire("Success", result.message , "success").then((value) => {
                                        window.location.replace('');
                                    });
                    $('.btn-mark-read').prop('disabled', false).html('Mark all as read')
                },
                error: function(res){
                    $('.btn-mark-read').prop('disabled', false).html('Mark all as read')
                }
            });
        })
    });

    const titleMarquee = (status = true) => {
        if(status){
            var titleText = document.title;
            titleText = titleText.substring(1, titleText.length) + titleText.substring(0, 1);
            document.title = titleText;
            setTimeout("titleMarquee()", 450);
        }else{
            return false;
        }
    }

</script>

resources/views/layouts/components/sidebar.blade.php
<!-- Main -->
<li class="nav-item-header">
    <div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i>
</li>

<li class="nav-item">
    <a href="{{ route('dashboard.index') }}" class="nav-link  {{ @$menu == 'Dashboard' ? 'active' : '' }} ">
        <i class="icon-home4"></i>
        <span>Dashboard</span>
    </a>
</li>

<li class="nav-item-header">
    <div class="text-uppercase font-size-xs line-height-xs">Features</div> <i class="icon-menu" title="Main"></i>
</li>

<li class="nav-item">
    <a href="{{ route('report.index') }}" class="nav-link  {{ @$menu == 'Reporting' ? 'active' : '' }} ">
        <i class="icon-list2"></i>
        <span>Reporting</span>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('ranking.index') }}" class="nav-link  {{ @$menu == 'Ranking' ? 'active' : '' }} ">
        <i class="icon-trophy2"></i>
        <span>Ranking</span>
    </a>
</li>

<li class="nav-item-header">
    <div class="text-uppercase font-size-xs line-height-xs">Main Master </div> <i class="icon-menu" title="Main"></i>
</li>

<li class="nav-item nav-item-submenu {{ @$menu == 'Master Data' ? 'nav-item-expanded nav-item-open' : '' }}">
    <a href="#" class="nav-link">
        <i class="icon-database"></i>
        <span>Master Data </span>
    </a>
    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
        <li class="nav-item"><a href="{{ route('category.index') }}" class="nav-link {{ @$submenu == 'Category' ? 'active' : '' }}">Category</a></li>
        <li class="nav-item"><a href="{{ route('report-level.index') }}" class="nav-link {{ @$submenu == 'Report Level' ? 'active' : '' }}">Report Level</a></li>
        <li class="nav-item"><a href="{{ route('risk-level.index') }}" class="nav-link {{ @$submenu == 'Risk Level' ? 'active' : '' }}">Risk Level</a></li>
    </ul>
</li>

<li class="nav-item-header">
    <div class="text-uppercase font-size-xs line-height-xs">Administration</div> <i class="icon-menu" title="Main"></i>
</li>
<li class="nav-item nav-item-submenu {{ @$menu == 'Users Management' ? 'nav-item-expanded nav-item-open' : '' }}">
    <a href="#" class="nav-link">
        <i class="icon-users"></i>
        <span>Users Management </span>
    </a>
    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
        <li class="nav-item"><a href="{{ route('users.index') }}" class="nav-link {{ @$submenu == 'Users List' ? 'active' : '' }}">Users List</a></li>
        <li class="nav-item"><a href="{{ route('roles.index') }}" class="nav-link {{ @$submenu == 'Roles List' ? 'active' : '' }}">Roles List</a></li>
        <li class="nav-item"><a href="{{ route('permissions.index') }}" class="nav-link {{ @$submenu == 'Permissions' ? 'active' : '' }}">Permissions</a></li>
    </ul>
</li>
<li class="nav-item">
    <a href="{{ route('menus.index') }}" class="nav-link  {{ @$menu == 'Menus' ? 'active' : '' }} ">
        <i class="icon-grid4"></i>
        <span>Menus</span>
    </a>
</li>
<li class="nav-item">
    <a href="{{ route('actions.index') }}" class="nav-link  {{ @$menu == 'Action' ? 'active' : '' }} ">
        <i class="icon-select2"></i>
        <span>Actions</span>
    </a>
</li>