routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes([
  // 'register' => true,
  // 'reset' => true,
  'verify' => true,
]);

Route::get('/forbidden', function () {
  return view('error.forbidden');
});

Route::group(['middleware' => ['verified']], function () {
  Route::get('/', 'HomeController@index')->name('dashboard');
  Route::get('/home', 'HomeController@index')->name('dashboard.index');
  Route::get('/dashboard', 'HomeController@index')->name('dashboard');

  Route::get('/notification', 'NotificationController@index');
  Route::get('/notification/get/{id?}', 'NotificationController@get');
  Route::get('/notification/read-all', 'NotificationController@read_all');
  Route::get('/notification/delete-all', 'NotificationController@delete_all');
  Route::get('/notification/view/{id?}', 'NotificationController@view');

  Route::get('/account', 'AccountController@show')->name('account');
  Route::post('/account/change-password', 'AccountController@change_password_process')->name('account.pass');
  Route::post('/account/update', 'AccountController@update_process')->name('account.update');
  Route::post('/account/update-fcm', 'AccountController@update_fcm')->name('account.update_fcm');
  Route::post('/account/update-avatar', 'AccountController@change_avatar_process')->name('account.avatar');

  Route::resource('roles', RoleController::class);
  Route::get('/roles/delete/{id?}', 'RoleController@destroy')->name('roles.delete');
  Route::post('/roles/update/{id?}', 'RoleController@update')->name('roles.update_process');

  Route::resource('permissions', PermissionController::class);
  Route::get('/permissions/delete/{id?}', 'PermissionController@destroy')->name('permissions.delete');
  Route::post('/permissions/update/{id?}', 'PermissionController@update')->name('permissions.update_process');

  Route::resource('users', UsersController::class);
  Route::get('/users/delete/{id?}', 'UsersController@destroy')->name('users.delete');
  Route::post('/users/update/{id?}', 'UsersController@update')->name('users.update_process');

  Route::resource('actions', ActionController::class);
  Route::get('/actions/delete/{id?}', 'ActionController@destroy')->name('actions.delete');
  Route::post('/actions/update/{id?}', 'ActionController@update')->name('actions.update_process');

  Route::resource('menus', MenuController::class);
  Route::get('/menus/delete/{id?}', 'MenuController@destroy')->name('menus.delete');
  Route::post('/menus/update/{id?}', 'MenuController@update')->name('menus.update_process');

  Route::resource('category', CategoryController::class);
  Route::get('/category/delete/{id?}', 'CategoryController@destroy')->name('category.delete');
  Route::post('/category/update/{id?}', 'CategoryController@update')->name('category.update_process');

  Route::resource('report-level', ReportLevelController::class);
  Route::get('/report-level/delete/{id?}', 'ReportLevelController@destroy')->name('report-level.delete');
  Route::post('/report-level/update/{id?}', 'ReportLevelController@update')->name('report-level.update_process');

  Route::resource('risk-level', RiskLevelController::class);
  Route::get('/risk-level/delete/{id?}', 'RiskLevelController@destroy')->name('risk-level.delete');
  Route::post('/risk-level/update/{id?}', 'RiskLevelController@update')->name('risk-level.update_process');

  Route::resource('report', ReportController::class);
  Route::get('/report/print/{id?}', 'ReportController@print')->name('report.print');
  Route::get('/report/delete/{id?}', 'ReportController@destroy')->name('report.delete');
  Route::post('/report/update/{id?}', 'ReportController@update')->name('report.update_process');

  Route::resource('ranking', RankingController::class);
});

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use DB;
use App\Menus;
use App\Action;

class PermissionController extends Controller
{
    private $data = [];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->data = [
                        'title'             => 'Permissions',
                        'subtitle'          => '',
                        'menu'              => 'Users Management',
                        'link_menu'         => '',
                        'icon_menu'         => 'icon-users',
                        'submenu'           => 'Permissions',
                        'link_submenu'      => '',
                        'icon_submenu'      => '',
                        'subsubmenu'        => '',
                        'icon_subsubmenu'   => '',
                        'route'             => 'permissions',
                        'permission'        => 'permissions',
                        'icon_primary'      => '',
                        'no'                => 1
                      ];
        $this->middleware("permission:".$this->data['permission']."-list", ['only' => ['index']]);
        $this->middleware("permission:".$this->data['permission']."-create", ['only' => ['create','store']]);
        $this->middleware("permission:".$this->data['permission']."-edit", ['only' => ['edit','update']]);
        $this->middleware("permission:".$this->data['permission']."-delete", ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->data['datatable'] = Permission::select('permissions.*', 'menus.name as menu_name')->join('menus', 'menus.id', '=', 'permissions.menu_id')->orderBy('menu_id','ASC')->get();
        return view($this->data['route'].'.index', $this->data);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['subtitle'] = 'Create Data';
        $this->data['menus'] = Menus::orderBy('name', 'ASC')->get();
        $this->data['actions'] = Action::get();
        return view('components.create', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:permissions,name',
            'menu_id' => 'required',
            'action_id' => 'required',
        ]);

        $query = Permission::create([
            'name' => $request->input('name'), 
            'menu_id' => $request->input('menu_id'),
            'action_id' => $request->input('action_id'),
        ]);

        if($query){
            return response()->json([
                    'status' => true,
                    '_token' => csrf_token(),
                    'message' => 'Add data success!',
                    'return_url' => $request->input('submit') == 'submit' ? url($this->data['route'].'/create') : url($this->data['route'])
                ]);
        }else{
            return response()->json([
                    'status' => false,
                    '_token' => csrf_token(),
                    'message' => 'Add data fail!',
                    'return_url' => '#'
                ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id = null)
    {
        $this->data['subtitle'] = 'Edit Data';
        $this->data['data_row'] = Permission::find($id);
        $this->data['menus'] = Menus::orderBy('name', 'ASC')->get();
        $this->data['actions'] = Action::get();
        return view('components.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id = null)
    {
        $this->validate($request, [
            'name' => 'required',
            'menu_id' => 'required',
            'action_id' => 'required',
        ]);

        $query = Permission::find($id);
        if($query->name != $request->input('name')){
            $this->validate($request, [
                'name' => 'required|unique:permissions,name',
            ]);
        }
        $query->name = $request->input('name');
        $query->menu_id = $request->input('menu_id');
        $query->action_id = $request->input('action_id');
        $query->save();

        if($query){
            return response()->json([
                    'status' => true,
                    '_token' => csrf_token(),
                    'message' => 'Update data success!',
                    'return_url' => $request->input('submit') == 'submit' ? "#edit-done" : url($this->data['route'])
                ]);
        }else{
            return response()->json([
                    'status' => false,
                    '_token' => csrf_token(),
                    'message' => 'Update data fail!',
                    'return_url' => '#'
                ]);
        }
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id = null)
    {
        $query = DB::table("permissions")->where('id',$id)->delete();
         if($query){
            return response()->json([
                    'status' => true,
                    '_token' => csrf_token(),
                    'message' => 'Delete data success!',
                    'return_url' => url($this->data['route'])
                ]);
        }else{
            return response()->json([
                    'status' => false,
                    '_token' => csrf_token(),
                    'message' => 'Delete data fail!',
                    'return_url' => '#'
                ]);
        }
    }
}

resources/views/permissions/form.blade.php
<form action="{{ $subtitle == 'Edit Data' ? route($route.'.update_process', @$data_row->id) : route($route.'.store') }}" method="post" class="form-validate-ajax" enctype="multipart/form-data" >
    @csrf
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group row">
                <label class="font-weight-semibold col-md-2 col-form-label">Menu  <span class="text-danger">*</span></label>
                <div class="col-md-10 pb-2">
                    <select type="text" class="form-control select-search-menu" id="menu_id" name="menu_id" placeholder="Enter" onchange="handleMenuChange(this)"  required >
                        <option value="">Choose One</option>
                        @foreach($menus as $menu)
                            <option value="{{ $menu->id }}" {{ $menu->id == @$data_row->menu_id ? 'selected' : ''}} >{{ $menu->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="font-weight-semibold col-md-2 col-form-label">Action  <span class="text-danger">*</span></label>
                <div class="col-md-10 pb-2">
                    <select type="text" class="form-control select-search-action" id="action_id" name="action_id" placeholder="Enter" onchange="handleActionChange(this)" required >
                        <option value="">Choose One</option>
                        @foreach($actions as $action)
                            <option value="{{ $action->id }}" {{ $action->id == @$data_row->action_id ? 'selected' : ''}} >{{ $action->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="font-weight-semibold col-md-2 col-form-label">Name Permission  <span class="text-danger">*</span></label>
                <div class="col-md-10">
                    <input type="text" class="form-control" id="name" name="name" value="{{ @$data_row->name }}" readonly >
                </div>
            </div>

            <br/>
            <div class="form-group">
                <input type="hidden" name="submit" id="submit-type" value="submit" />
                <button type="submit"  id="submit" value="submit" class="btn bg-transparent text-blue border-blue mr-2 btn-submit" onclick="(function(){$('#submit-type').val('submit');return true;})();return true;">Submit<i class="icon-paperplane ml-2"></i></button>
                <button type="submit"  id="submit-back" value="submit-back" class="btn bg-transparent text-blue border-blue mr-2 btn-submit-back" onclick="(function(){$('#submit-type').val('submit-back');return true;})();return true;">Submit & Back<i class="icon-paperplane ml-2"></i></button>
            </div>
        </div>
    </div>
</form>

<script>
    $( document ).ready(function() {
        var $select = $('.select-search-menu').select2({
            allowClear: true,
            escapeMarkup: function (markup) { return markup; },
            placeholder: "Choose One",
            language: {
                noResults: function () {
                    return `<a href="{{ route('menus.create') }}"><i class='icon-plus2'></i> Tambah menu baru</a>`;
                }
            }
        });

        var $select = $('.select-search-action').select2({
            allowClear: true,
            escapeMarkup: function (markup) { return markup; },
            placeholder: "Choose One",
            language: {
                noResults: function () {
                    return `<a href="{{ route('actions.create') }}"><i class='icon-plus2'></i> Tambah action baru</a>`;
                }
            }
        });
    })

    const handleMenuChange = (param) => {
        if($('#action_id').val() == ''){
            return false;
        }
        let menu = $(param).find(":selected").text().toLowerCase().replace(" ", "-");
        let action = $('#action_id').find(":selected").text().toLowerCase().replace(" ", "-");
        $('#name').val(menu+'-'+action)
    }

    const handleActionChange = (param) => {
        if($('#menu_id').val() == ''){
            return false;
        }
        let action = $(param).find(":selected").text().toLowerCase().replace(" ", "-");
        let menu = $('#menu_id').find(":selected").text().toLowerCase().replace(" ", "-");
        $('#name').val(menu+'-'+action)
    }
</script>

resources/views/permissions/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Content area -->
<div class="content">
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title"><i class="{{ $icon_primary ?? '' }}"></i> {{ $title }} </h5>
            <div class="header-elements">
                <div class="list-icons">
                    @can($permission.'-create')
                        <a href="{{ route($route.'.create') }}" class="list-icons-item btn btn-md bg-{{ config('app.theme') }}"> <i class="icon-plus2 mr-1"></i> Tambah Data</a>
                    @endcan
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="tab-content">
                <div class="tab-pane fade show active" id="highlighted" style="margin-top:-20px;">
                    <table class="table datatable-button-html5-columns no-wrap" >
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Menu</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($datatable as $key => $row)
                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>{{ $row->name }}</td>
                                    <td>{{ $row->menu_name }}</td>
                                    <td class=''>
                                        <div class="list-icons">
                                            <div class="dropdown">
                                                <a href="#" class="list-icons-item" data-toggle="dropdown">
                                                    <i class="icon-menu9"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    @can($permission.'-edit')
                                                        <a href="{{ route($route.'.edit', $row->id) }}" class="dropdown-item"><i class="icon-pencil5"></i> Edit</a>
                                                    @endcan
                                                    @can($permission.'-delete')
                                                        <a href="#remove" data-toggle="confirm-remove" data-address="{{ route($route.'.delete', $row->id) }}" type="button" class="dropdown-item" ><i class="icon-trash-alt"></i> Delete </a>
                                                    @endcan
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection